apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default  # <--- This is the missing line!
  source:
    repoURL: 'http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/abelfany.git'
    path: overlays
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: nginx
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: 'https://github.com/aelfany/agro'
#     path: overlays
#     targetRevision: main
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: default
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true

