apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo-credentials
  namespace: argocd
  labels:
stringData:
  type: git
  url: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/abelfany.git
  username: root
  password: ${GITLAB_TOKEN}