apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  # Your translated internal link
  url: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/abelfany.git
  username: root
  # Paste the Personal Access Token you generated in GitLab here
  password: ${GITLAB_TOKEN}