Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "abelfanyS" do |server|
    server.vm.hostname = "abelfanyS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.name = "abelfanyS"
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/install_k3s.sh"
  end
end