Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"
  config.vm.define "ael-kaceS" do |server| 
    server.vm.hostname = "ael-kaceS"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "ael-kace.s"
      vb.memory = "2048"
      vb.cpus = "2"
    end
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder "./", "/vagrant", type: "rsync"
    server.vm.provision "shell", path: "scripts/server_installation.sh"
  end
end