Vagrant.configure("2") do |config|
  
  #server machine 
  config.vm.define "abelfany" do |debian|

    debian.vm.hostname = "abelfanyS"
    debian.vm.box = "bento/debian-12"

    debian.vm.network "private_network", ip: "192.168.56.110"
    debian.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.name = "abelfany"
      vb.cpus = 1
    end
  end
  #server worker machine 
  config.vm.define "kacem" do |ubuntu|

    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.hostname = "kacemS"

    ubuntu.vm.network "private_network", ip: "192.168.56.111"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.name = "kacem"
      vb.cpus = 1
    end
  end

end
