Vagrant.configure("2") do |config|
  
  # Master Server
  config.vm.define "abelfanyS" do |debian|
    debian.vm.hostname = "abelfanyS"
    debian.vm.box = "bento/debian-12"
    debian.vm.provision "shell", path: "scripts/install_k3s_server.sh"
    debian.vm.network "private_network", ip: "192.168.56.110"
    debian.vm.provider "virtualbox" do |vb|
      vb.memory = "1024" 
      vb.name = "abelfany"
      vb.cpus = 1
    end
  end

  config.vm.define "ael-kaceSW" do |ubuntu|
    ubuntu.vm.box = "ubuntu/jammy64"
    ubuntu.vm.hostname = "ael-kaceSW"
    ubuntu.vm.provision "shell", path: "scripts/install_k3s_worker.sh"
    ubuntu.vm.network "private_network", ip: "192.168.56.111"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "ael-kace"
      vb.cpus = 1
    end
  end
end