apiVersion: v1
kind: Service
metadata:
  name: app-one-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: app-one
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - name: app-one
          image: hashicorp/http-echo
          args:
            - "-text=Hello From App1 by Kacimo!"
          ports:
            - containerPort: 5678