Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "test" do |server|
    server.vm.hostname = "test-machine"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.network "forwarded_port", guest: 8080, host: 8080

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048 
      vb.name = "test"
      vb.cpus = 1
    end
  end
end