Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "test" do |gg|
    gg.vm.hostname = "test-machine"
    gg.vm.network "private_network", ip: "192.168.56.111"
    gg.vm.network "forwarded_port", guest: 9090, host: 9090 

    gg.vm.provider "virtualbox" do |vb|
      vb.memory = 2048 
      vb.name = "test"
      vb.cpus = 1
    end
  end


  config.vm.box = "ubuntu/jammy64"

  config.vm.define "work" do |server|
    server.vm.hostname = "work-machine"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.network "forwarded_port", guest: 80, host: 80
    server.vm.network "forwarded_port", guest: 443, host: 443
    # Keep 8080 just in case you need direct API access
    server.vm.network "forwarded_port", guest: 8080, host: 8080
    server.vm.synced_folder ".", "/home/vagrant/shared", 
    owner: "vagrant", 
    group: "vagrant", 
    mount_options: ["dmode=775,fmode=664"]
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048 
      vb.name = "work"
      vb.cpus = 1
    end
  end
end